locker: Only get `CoreTap.instance.git_head` if not using the API
- Before, the lockfile would try to populate with `CoreTap.instance.git_head`
  which doesn't exist when using the API (now the default), leading to this
  error for the user:

```
> brew bundle --file=testBrewfile
Using asdf
Error: No available tap homebrew/core.
```

Now:

```
> brew bundle --file=testBrewfile
Using asdf
Homebrew Bundle complete! 1 Brewfile dependency now installed.

❯ tail testBrewfile.lock.json
        "HOMEBREW_VERSION": "4.0.1-60-gf0bcef6-dirty",
        "HOMEBREW_PREFIX": "/opt/homebrew",
        "Homebrew/homebrew-core": "api",
        "CLT": "14.1.0.0.1.1666437224",
        "Xcode": "14.1",
        "macOS": "13.0"
      }
    }
  }
}
```