Don't lowercase URL when those are specified in Brewfile
If a Brewfile defines a specific version of a package and this
package originates form an URL, the name shouldn't be lowercase.

An example of such file could be:

```
brew "https://raw.githubusercontent.com/Homebrew/homebrew-core/50c928c870001577ce6b7e28edf43e05df699852/Formula/etcd.rb"
```

Previous to this case this was falling with this error:

```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing; `/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.11\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --fail --progress-bar --retry 3 --location --remote-time --continue-at 0 --output /Users/alexandru/Library/Caches/Homebrew/Formula/etcd.rb https://raw.githubusercontent.com/homebrew/homebrew-core/50c928c870001577ce6b7e28edf43e05df699852/formula/etcd.rb` exited with 22. Here's the output:

curl: (22) The requested URL returned error: 404 Not Found
```

The reason of the failure was due to the name been transformed
to lowercase.